AspFood/Models/ErrorViewModel.cs
namespace AspFood.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspFood/Controllers/ContactController.cs
using BLL.Abstract;
using DTO.DtoEntity;
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{
    public class ContactController : Controller
    {
        private readonly IMessage _message;

        public ContactController(IMessage message)
        {
            _message = message;
        }

        public IActionResult Index(MessageDto dto)
        {
            _message.Insert(dto);
            ViewBag.mesaj = "Qeyde edildi...";
            return View();
        }
    }
}

AspFood/Controllers/HomeController.cs
using BLL.Abstract;
using BLL.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMenu _menuservice;

        public HomeController(IMenu menuservice)
        {
            _menuservice = menuservice;
        }

        public IActionResult Index()
        {
            var values=_menuservice.GetCategoryInclude();
            ViewBag.c = _menuservice.GetCategoryInclude().Where(x => x.CategoryName == "Pizzalar");
            return View(values);
        }


    }
}

AspFood/Controllers/ReviewController.cs
using BLL.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ICustomer _customer;

        public ReviewController(ICustomer customer)
        {
            _customer = customer;
        }

        public IActionResult Index()
        {
            var values = _customer.GetAll();
            return View(values);
        }
    }
}

AspFood/Controllers/SearchController.cs
using BLL.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{

    public class SearchController : Controller
    {
        private readonly IMenu _menu;

        public SearchController(IMenu menu)
        {
            _menu = menu;
        }

        public IActionResult Index(string search)
        {
            var values = from x in _menu.GetCategoryInclude() select x;
            if (!string.IsNullOrEmpty(search))
            {
                values = values.Where(x => x.Title.ToLower().Contains(search.ToLower()));
            }
            return View(values);
          
        }
    }
}

AspFood/Controllers/SendMessageController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{
    public class SendMessageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspFood/Controllers/SpecialController.cs
using BLL.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace AspFood.Controllers
{
    public class SpecialController : Controller
    {
        private readonly IMenu _menu;

        public SpecialController(IMenu menu)
        {
            _menu = menu;
        }

        public IActionResult Index()
        {
            var values = _menu.GetCategoryInclude().Where(x=>x.CategoryName=="Burgerlər");
            return View(values);
        }
    }
}

AspFood/Views/About/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<section class="about" id="about">
    <h1 class="heading">Bizim <span>Haqqımızda</span></h1>
    <div class="row">
        <div class="image">
            <img src="~/website/images/about.jpg" alt="about" />
        </div>
        <div class="content">
            <h3>What Is The Secret Recipe Of Our Burgers?</h3>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat enim
                adipisci minima dolorem, explicabo quos obcaecati sunt quasi?
                Laborum, ipsum.
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat enim
                adipisci minima dolorem, explicabo quos obcaecati sunt quasi?
                Laborum, ipsum.
            </p>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat enim
                adipisci minima dolorem, explicabo quos obcaecati sunt quasi?
                Laborum, ipsum.
            </p>
            <a href="#" class="btn">Learn More</a>
        </div>
    </div>
</section>

AspFood/Views/Contact/Index.cshtml
@model DTO.DtoEntity.MessageDto
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<section class="contact" id="contact">
    <h1 class="heading">Bizimlə əlaqə </h1>
    <div class="row">
        <iframe class="map"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d945551.4822276899!2d44.875538067703346!3d39.97812726841381!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307d6bd6211cf9%3A0x343f6b5e7ae56c6b!2zQmFrw7w!5e0!3m2!1str!2saz!4v1709019119180!5m2!1str!2saz"
                loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        <form asp-controller="SendMessage" asp-action="Index" method="post" >
            <h3>Əlaqə saxla</h3>
            <div class="inputBox">
                <i class="fas fa-user"></i>
                <input type="text" asp-for=Name placeholder="Ad" />
            </div>
            <div class="inputBox">
                <i class="fas fa-envelope"></i>
                <input type="email" asp-for=Email placeholder="Email" />
            </div>
            <div class="inputBox">
                <i class="fas fa-phone"></i>
                <input type="number" asp-for=Phone placeholder="Telefon nömrəsi" />
            </div>
            <input type="submit" class="btn"  value="Göndər" />
        </form>
    </div>
</section>

AspFood/Views/Home/Index.cshtml
@model IEnumerable<DTO.DtoEntity.MenuDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<section class="menu" id="menu">
    <h1 class="heading">Standart <span>menyular</span></h1>
    <div class="box-container">
        @foreach(var item in ViewBag.c)
        {
            <div class="box">
                <div class="box-head">
                    <img src="@item.Image" alt="menu" />
                    <span class="menu-category">@item.CategoryName</span>
                    <h3>@item.Title</h3>
                    <div class="price">@item.DisCount Azn <span>@item.Price Azn</span></div>
                </div>
                <div class="box-bottom">
                    <a href="#" class="btn">sifarış ver</a>
                </div>
            </div>
        }
    </div>
</section>
<!-- Menu Section End -->
<!-- Products Section Start -->
<section class="products" id="products">
    <h1 class="heading">Özəl <span>menyular</span></h1>
    <div class="box-container">
        @foreach (var item in Model)
        {
            <div class="box">
                <div class="box-head">
                    <span class="title">@item.CategoryName</span>
                    <a href="#" class="name">@item.Title</a>
                </div>
                <div class="image">
                    <img src="@item.Image" alt="products" />
                </div>
                <div class="box-bottom">
                    <div class="info">
                        <b class="price">@item.Price Azn</b>
                        <span class="amount">@item.Gram gr / @item.Calory Calory</span>
                    </div>
                    <div class="product-btn">
                        <a href="#">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

AspFood/Views/Partials/_Banner.cshtml
<section class="home" id="home">
    <div class="content">
        <h3>EXPRESS HOME DELIVERY</h3>
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis iusto
            vel minima hic quaerat error!
        </p>
        <a href="#" class="btn">Order Now</a>
    </div>
</section>

AspFood/Views/Partials/_Footer.cshtml
<section class="footer">

    <div class="share">
        <a href="#" class="fab fa-facebook"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-instagram"></a>
        <a href="#" class="fab fa-linkedin"></a>
        <a href="#" class="fab fa-pinterest"></a>
    </div>
    <div class="links">
        <a asp-controller="Home" asp-action="Index" class="active">Menyular</a>
        <a asp-controller="Special" asp-action="Index">Özəl</a>
        <a asp-controller="About" asp-action="Index">Haqqımızda</a>
        <a asp-controller="Contact" asp-action="Index">Bizimlə Əlaqə</a>
        <a asp-controller="Review" asp-action="Index">Rəylər</a>
    </div>
    <div class="credit">
        created by <span>Kamil Rustemli</span> | all right reserved
    </div>
</section>

AspFood/Views/Partials/_Header.cshtml
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/website/css/style.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet" />
    <title>Restaurant webSite</title>
</head>

AspFood/Views/Partials/_NavBar.cshtml
<header class="header">
    <a class="logo" href="#">
        <img src="~/website/images/logo.png" alt="logo" />
    </a>
    <nav class="navbar">
        <a asp-controller="Home" asp-action="Index" class="active">Menyular</a>
        <a asp-controller="Special" asp-action="Index">Özəl</a>
        <a asp-controller="About" asp-action="Index">Haqqımızda</a>
        <a asp-controller="Contact" asp-action="Index">Bizimlə Əlaqə</a>
        <a asp-controller="Review" asp-action="Index">Rəylər</a>
    </nav>


    <div class="buttons">
        <button id="search-btn">
            <i class="fas fa-search"></i>
        </button>
        <button id="cart-btn">
            <i class="fas fa-shopping-cart"></i>
        </button>
        <button id="menu-btn">
            <i class="fas fa-bars"></i>
        </button>
    </div>
        <form asp-controller="Search" asp-action="Index" method="get">
    <div class="search-form">
            <input type="text" class="search-input" name="search" id="search-box" placeholder="search-here">
            <i class="fas fa-search"></i>
        </form>
    </div>

    <div class="cart-items-container">
        <div class="cart-item">
            <i class="fas fa-times"></i>
            <img src="~/website/images/menu-1.png" alt="menu">
            <div class="content">
                <h3>cart item 01</h3>
                <div class="price">$15.99/-</div>
            </div>
        </div>
        <div class="cart-item">
            <i class="fas fa-times"></i>
            <img src="./images/menu-2.png" alt="menu">
            <div class="content">
                <h3>cart item 02</h3>
                <div class="price">$15.99/-</div>
            </div>
        </div>
        <div class="cart-item">
            <i class="fas fa-times"></i>
            <img src="~/website/images/menu-3.png" alt="menu">
            <div class="content">
                <h3>cart item 03</h3>
                <div class="price">$15.99/-</div>
            </div>
        </div>
        <div class="cart-item">
            <i class="fas fa-times"></i>
            <img src="~/website/images/menu-4.png" alt="menu">
            <div class="content">
                <h3>cart item 04</h3>
                <div class="price">$15.99/-</div>
            </div>
        </div>
        <a href="#" class="btn">Checkout Now</a>
    </div>
    <!--bu en axirdadi responsivlikde-->
</header>

AspFood/Views/Partials/_Review.cshtml
@await Component.InvokeAsync("ReviewList")

AspFood/Views/Review/Index.cshtml
@model IEnumerable<DTO.DtoEntity.CustomerDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ReviewLayout.cshtml";
}

<section class="review" id="review">
    <h1 class="heading">Müştəri <span>rəyləri</span></h1>
    <div class="box-container">

        @foreach (var item in Model)
        {
            <div class="box">
                <img src="~/website/images/quote.png" alt="quote" />
                <p>
                    @item.Text
                </p>
                <img src="@item.Image" alt="avatar" class="user" />
                <h3>@item.FirstName</h3>
                <div class="stars">
                    @for (int i = 0; i < Convert.ToInt32(item.Rate); i++)
                    {
                        <i class="fa-solid fa-star"></i>
                    }
                    @for (int i = 0; i < 5 - Convert.ToInt32(item.Rate); i++)
                    {
                        <i class="fa-regular fa-star"></i>
                    }



                </div>
            </div>
        }
    </div>
</section>

AspFood/Views/Search/Index.cshtml
@model IEnumerable<DTO.DtoEntity.MenuDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}



<section class="products" id="products">
    <h1 class="heading">Özəl <span>menyular</span></h1>
    <div class="box-container">
        @foreach (var item in Model)
        {
            <div class="box">
                <div class="box-head">
                    <span class="title">@item.CategoryName</span>
                    <a href="#" class="name">@item.Title</a>
                </div>
                <div class="image">
                    <img src="@item.Image" alt="products" />
                </div>
                <div class="box-bottom">
                    <div class="info">
                        <b class="price">@item.Price Azn</b>
                        <span class="amount">@item.Gram gr / @item.Calory Calory</span>
                    </div>
                    <div class="product-btn">
                        <a href="#">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

AspFood/Views/SendMessage/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<partial name="~/Views/Partials/_Header.cshtml" />
<body>
    <!-- Header Section Start -->
    <partial name="~/Views/Partials/_Navbar.cshtml" />
    <!-- Header Section End -->
    <h1 class="heading">  Mesajınız uğurla göndərildi...</h1>
    <!-- Footer Section Start -->
    <partial name="~/Views/Partials/_Footer.cshtml" />
    <!-- Footer Section End -->

    <script type="text/javascript" src="~/website//app.js"></script>
</body>
</html>

AspFood/Views/Shared/Components/ReviewList/Default.cshtml
@model IEnumerable<DTO.DtoEntity.CustomerDto>
@{
    Layout = null;
}

<section class="review" id="review">
    <h1 class="heading">Müştəri <span>rəyləri</span></h1>
    <div class="box-container">
      
        @foreach(var item in Model)
        {
            <div class="box">
                <img src="~/website/images/quote.png" alt="quote" />
                <p>
                    @item.Text
                </p>
                <img src="@item.Image" alt="avatar" class="user" />
                <h3>@item.FirstName</h3>
                <div class="stars">
                    @for (int i = 0; i < Convert.ToInt32(item.Rate); i++)
                    {
                        <i class="fa-solid fa-star"></i>
                    }
                    @for (int i = 0; i < 5 - Convert.ToInt32(item.Rate); i++)
                    {
                        <i class="fa-regular fa-star"></i>
                    }



                </div>
            </div>
        }
    </div>
</section>

AspFood/Views/Shared/_HomeLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<partial name="~/Views/Partials/_Header.cshtml" />
<body>
    <!-- Header Section Start -->
    <partial name="~/Views/Partials/_Navbar.cshtml" />
    <!-- Header Section End -->
    <!-- Home Section Start -->
    <partial name="~/Views/Partials/_Banner.cshtml" />
    <!-- Home Section End -->
    <!-- Menu Section Start -->
    @RenderBody()
    <!-- Products Section End -->
    <!-- Review Section Start -->
    <partial name="~/Views/Partials/_Review.cshtml" />
    <!-- Review Section End -->
    <!-- Footer Section Start -->
    <partial name="~/Views/Partials/_Footer.cshtml" />
    <!-- Footer Section End -->

    <script type="text/javascript" src="~/website//app.js"></script>
</body>
</html>

AspFood/Views/Shared/_PageLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<partial name="~/Views/Partials/_Header.cshtml" />
<body>
    <!-- Header Section Start -->
    <partial name="~/Views/Partials/_Navbar.cshtml" />
    <!-- Header Section End -->
    <!-- Menu Section Start -->
    @RenderBody()
    <!-- Products Section End -->
    <!-- Review Section Start -->
    <partial name="~/Views/Partials/_Review.cshtml" />
    <!-- Review Section End -->
    <!-- Footer Section Start -->
    <partial name="~/Views/Partials/_Footer.cshtml" />
    <!-- Footer Section End -->

    <script type="text/javascript" src="~/website//app.js"></script>
</body>
</html>

AspFood/Views/Shared/_ReviewLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<partial name="~/Views/Partials/_Header.cshtml" />
<body>
    <!-- Header Section Start -->
    <partial name="~/Views/Partials/_Navbar.cshtml" />
    <!-- Header Section End -->
    <!-- Menu Section Start -->
    @RenderBody()
    <!-- Products Section End -->
    <!-- Footer Section Start -->
    <partial name="~/Views/Partials/_Footer.cshtml" />
    <!-- Footer Section End -->

    <script type="text/javascript" src="~/website//app.js"></script>
</body>
</html>

AspFood/Views/Special/Index.cshtml
@model IEnumerable<DTO.DtoEntity.MenuDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<section class="products" id="products">
    <h1 class="heading">Özəl <span>menyular</span></h1>
    <div class="box-container">
        @foreach(var item in Model)
        {
            <div class="box">
                <div class="box-head">
                    <span class="title">@item.CategoryName</span>
                    <a href="#" class="name">@item.Title</a>
                </div>
                <div class="image">
                    <img src="@item.Image" alt="products" />
                </div>
                <div class="box-bottom">
                    <div class="info">
                        <b class="price">@item.Price azn</b>
                        <span class="amount">@item.Gram gr / @item.Calory Cal</span>
                    </div>
                    <div class="product-btn">
                        <a href="#">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>
        }

    </div>
</section>